package com.exceedgulf.alainzoo.preference;

/**
 * Created by Paras Ghasadiya on 19/12/17.
 */

public interface PrefCons {
    String IS_FIRST_TIME = "IS_FIRST_TIME";
    String APP_LANGUAGE = "APP_LANGUAGE";
    String APPLICATION_TOKEN_EXPIRES = "APPLICATION_TOKEN_EXPIRES";
    String APPLICATION_TOKEN = "APPLICATION_TOKEN";
    String APPLICATION_TOKEN_BEARER = "APPLICATION_TOKEN_BEARER";
    String APPLICATION_TOKEN_CREATED = "APPLICATION_TOKEN_CREATED";
    String REFRESH_TOKEN = "REFRESH_TOKEN";
    String IS_LOGGEDIN = "IS_LOGGEDIN";
    String USERNAME = "USERNAME";
    String PASSWORD = "PASSWORD";
    String LOGOUT_TOKEN = "LOGOUT_TOKEN";
    String CSRF_TOKEN = "CSRF_TOKEN";
    String USER_DOB = "USER_DOB";
    String USER_EMIRATE = "USER_EMIRATE";
    String USER_EMIRATE_ID = "USER_EMIRATE_ID";
    String USER_GENDER = "USER_GENDER";
    String USER_MOBILE = "USER_MOBILE";
    String USER_FIELD_NAME = "USER_FIELD_NAME";
    String USER_NATIONALITY = "USER_NATIONALITY";
    String USER_NATIONALITY_ID = "USER_NATIONALITY_ID";
    String USER_LANG_CODE = "USER_LANG_CODE";
    String USER_EMAIL = "USER_EMAIL";
    String USER_NAME = "USER_NAME";
    String USER_AVATAR_ID = "USER_AVATAR_ID";
    String USER_UID = "USER_UID";
    String USER_UUID = "USER_UUID";
    String USER_POINTS = "USER_POINTS";
    String USER_TOTAL_POINTS = "USER_TOTAL_POINTS";
    String PARKING_LOCATION = "PARKING_LOCATION";
    String SHOW_TUTORIAL = "SHOW_TUTORIAL";
    String IS_TEMP_LOGGEDIN = "IS_TEMP_LOGGEDIN";
    String BEACON_NOTIFICATION = "BEACON_NOTIFICATION";
    String ONESIGNAL_NOTIFICATION = "ONESIGNAL_NOTIFICATION";
    String MY_PLANE_DELETE_LAST_TIME = "MY_PLANE_DELETE_LAST_TIME";
}
